### ISSUE TITLE
[TASK] Responsive Breakpoints for Bridge dApp

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#106]
## Overview
As we continue to enhance the Bridge dApp, we need to create additional breakpoints to ensure that it is responsive to a wider range of screen sizes. The current breakpoints are not sufficient to accommodate all users, especially those with smaller screensizes. To address this issue, we need to design additional breakpoints to ensure a consistent and optimal user experience across all devices and screen sizes.

### Tasks:
- Review the current breakpoints and assess the gaps in screen sizes that need to be addressed.
- Research best practices for additional breakpoints and analyze how other apps have addressed similar issues.
- Design wireframes for each breakpoint to ensure a consistent and optimal user experience across all screen sizes.

**Comment by monaiuu** [comment]
## Handoff

The responsive breakpoints for the Bridge DApp have been completed and are ready for implementation. The breakpoints define screen sizes for a consistent & optimized user experience.  At each breakpoint, the site adapts its layout to better fit the available screen space to display the most important components. 

### Notes:

- At the `480px` breakpoint, the layout switches to a one-column layout displaying only the bridge control card.
- Selective table items will be hidden as interface hits smaller breakpoints (reference below)
- Add mobile footer component to design system

### Handoff Wireframes
Can be found in the page 🛠 **Responsive Breakpoints** within the **🌉  Bridge UI v1** Figma File.
https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=2967%3A361717&t=HvZSPkhfKBciJzgP-1

### Screen Recording


https://user-images.githubusercontent.com/109539270/228069800-5b6c1d08-b7cb-49bc-adf4-92f177a29414.mp4

**Comment by dutterbutter** [comment]
Closing for dev handoff: https://github.com/webb-tools/webb-dapp/issues/1085
