### ISSUE TITLE
[TASK] Create technical diagrams for single asset shielded pool protocol

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#110]
## Objective

To create visually appealing and easy-to-understand technical diagrams for Webb's documentation site, which will help users understand technical concepts more effectively and improve our ability to communicate the protocol. 

### Scope

The scope of work for this task will be focused on delivering technical diagrams for Webb's single asset shielded privacy pools that references the TNT asset. Other technical diagrams such as, multi-asset shielded pools, and light client related will be done subsequently.  

### Diagram Deliverables

- [ ] Webb's single asset shielded privacy pools with TNT

### Technical Diagram

The intended diagram should visually describe how single asset shielded privacy pools work, with specific details regarding resourceID usage, and distinctions between EVM and Substrate assets. 

#### Example Diagram 

<img width="1230" alt="CleanShot 2023-03-28 at 09 40 25@2x" src="https://user-images.githubusercontent.com/29983536/228274793-fc67d564-0cf2-4d7e-9554-6c6ea058c1e9.png">

**Comment by dutterbutter** [comment]
Started additional technical diagrams [here](https://excalidraw.com/).

**Comment by monaiuu** [comment]
Link: https://excalidraw.com/#room=7c6f09524b6097d44684,NPLSmXObIt69rOPTtJLTww
