### ISSUE TITLE
[TASK] Create Thumbnail Templates for Webb Blog Posts

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#118]

**Comment by monaiuu** [comment]
## Update

This task is completed; the proposed template can be seen below:

![Image](https://user-images.githubusercontent.com/109539270/235201529-73330113-8395-4a46-88f4-debb032b0947.png)


However, @thomivy  has suggested updating the blog card components as below to be more texts focused.

![Image](https://user-images.githubusercontent.com/109539270/235200872-cd519340-1185-4ffa-b9a2-3d152a87daef.png)

With this in mind, a thumbnail template may no longer be needed. However, having a standardized SEO image for each blog post would still be good. Further exploration and discussion are required.

**Comment by thomivy** [comment]
We'll still need a card template for social sharing schemas, so still good to have this regardless of the gallery display
