### ISSUE TITLE
[TASK] Notion Doc for Webb Brand Kit Assets

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#137]
## Description

Create a Notion doc to gather all required assets to be downloaded for Webb Brand Kit.

- [x] Webb Logos/Logomarks
- [x] Typographies
- [x] Colour Palettes PDF 
- [x] Iconography

**Comment by monaiuu** [comment]
### File Access

See all required assets to be downloaded from Webb Brand Kit here:
https://www.notion.so/hicommonwealth/Webb-Brand-Kit-7ba65237a47640edb13dee499ae28a30?pvs=4

Please reference [Polkadot's Brand Hub](**url**) in organizing the assets for download.

**Comment by dutterbutter** [comment]
Closing as completed and handed off here: https://github.com/webb-tools/webb-dapp/issues/1129
