### ISSUE TITLE
[TASK] Create Incentive Campaign Page on Tangle site

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#144]
## Description

Need a section for the incentive campaign, or a separate page:

**Tangle Testnet Incentive Campaign**
As we prepare for the launch of the Tangle Network, we're excited to announce our Testnet Incentive Campaign! This program is designed to encourage users to explore, utilize, and improve the Tangle Network, contributing to the development of cutting-edge privacy tooling. By participating in various activities, users can earn points that will entitle them to a percentage of the Tangle Network's airdrop.

**Points Scheme**

| Activity                                           | Points    |
|----------------------------------------------------|-----------|
| Relay 1 tx/day for 1 week/month                    | 0         |
| Make 1 deposit over X amount                       | 0         |
| Make 1 withdraw                                    | 0         |
| Run a validator                                    | 1         |
| DKG Authority (get voted in)                       | 5         |
| Bug Bounty with PR Fix Submission                  | 50        |
| Deposit → Transfer → Withdraw                      | 10        |
| Vote in Governance                                 | 1         |
| Propose and Pass in Governance                     | 1         |
| Author a Protocol Extension                        | 3         |
| Scripts to make Transactions                       | 10        |
| Publish a video or tutorial on Tangle or Webb.     | 20        |
| Tweet about Webb                                   | 3         |
| Tweet a Semaphore identity w/ Webb                 | 20        |
| Tweet an ETH address or ENS domain                 | 15        |
| Tweet a hash of your address + a secret number     | 20        |
| Bug Report                                         | 10        |
| Use Case Concepts (Asset protocols, Maps, Identity, Social) | 10   |
| Creative Contribution — Have an idea for something that doesnt fit here? Show us! We’ll assign points based on merit. | Variable |

CTA: Join our Discord's Testnet channel to participate, report your contributions, and more. (JOIN)

Reference:
https://github.com/webb-tools/webb-dapp/issues/1137#issuecomment-1535561024

**Comment by monaiuu** [comment]
@thomivy If you see any examples we can reference, share them below!

**Comment by drewstone** [comment]
## Examples
- https://phase2.testnet.ironfish.network/leaderboard
- https://phase2.testnet.ironfish.network/users/60767
- https://aleoambassadors.org/leaderboard/

**Comment by drewstone** [comment]
We may want to increase the # of points for validating and running infra truly.

**Comment by monaiuu** [comment]
| Activity                                           | Points    | Type | Category |
|----------------------------------------------------|-----------|------|----------|
| Relay 1 tx/day for 1 week/month                    | 0         | On-chain | Relayer |
| Make 1 deposit over X amount                       | 0         | On-chain | Transaction |
| Make 1 withdraw                                    | 0         | On-chain | Transaction |
| Run a validator                                    | 1         | On-chain | Validator |
| DKG Authority (get voted in)                       | 5         | On-chain | Governance |
| Bug Bounty with PR Fix Submission                  | 50        | Off-chain | Reporter |
| Deposit → Transfer → Withdraw                      | 10        | On-chain | Transaction |
| Vote in Governance                                 | 1         | On-chain | Governance |
| Propose and Pass in Governance                     | 1         | On-chain | Governance |
| Author a Protocol Extension                        | 3         | Off-chain | Creator |
| Scripts to make Transactions                       | 10        | Off-chain | Transaction |
| Publish a video or tutorial on Tangle or Webb.     | 20        | Off-chain | Creator |
| Tweet about Webb                                   | 3         | Off-chain | Creator |
| Tweet an ETH address or ENS domain                 | 15        | Off-chain | Creator |
| Tweet a hash of your address + a secret number     | 20        | Off-chain | Creator |
| Bug Report                                         | 10        | Off-chain | Reporter |
| Use Case Concepts (Asset protocols, Maps, Identity, Social) | 10   | Off-chain | Innovator |
| Creative Contribution — Have an idea for something that doesn't fit here? Show us! We’ll assign points based on merit. | Variable | Off-chain | Innovator |
