### ISSUE TITLE
[TASK] Spec out MASP integration to Hubble Bridge

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#209]
## Description
Spec out the integration Multi Asset Shielded Pool (MASP) alongside the existing Single Asset Shielded Pool (SASP) deployment on Hubble Bridge. 

- Conduct initial evaluation to understand the technical requirements for integrating MASP into Hubble.

- Access current UI to identify the necessary adjustments for accommodating MASP flow, whilst ensuring design adjustments are minimal.
- Identify the necessary adjustments for accommodating MASP note account into account dashboard

**Comment by drewstone** [comment]
Claim rewards page will be included here too.

**Comment by monaiuu** [comment]
Initial spec is completed here: https://www.notion.so/hicommonwealth/Design-Kickoff-26d661f713054e239a733410dcb663f1?pvs=4
