### ISSUE TITLE
[TASK] Optimize Tangle Site

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-experiences#241]
From Slack:

Firstly, we have to likely clean up templates a lot, I’m not sure we ever cleaned them up yet since we started the webflow migration. But basically I see the following that I think messes up load times w/ size issues.

Using templates from webflow and auxiliary pages: We have to actually delete things we’re not using or put them in draft mode or else they’ll be published and increase the size of the site, making load time large.

Cleaning up template images and reducing our own image sizes: I can see many instances of images from the template that are present in the project. Unsure if they’re being roped in but a site load service clocks our site at 64MB which is super large. We need to remove all these images. We also have lots of images that are oversized and I don’t actually see them being used. Maybe we remove those too. The project needs to be clean and essentials 

Cleaning up unused scripts/javascript: 
Thom you mentioned this maybe you can help clean that up?

Font optimization: Maybe we can improve font optimization here.
Unused pages: I see a couple unused pages that add to build size like “Dashboard”, it seems unfinished and I’ll move into draft but make sure things that don’t need to be published don’t get published.

Here’s a report from online about some other things we can fix:
 https://pagespeed.web.dev/analysis/https-tangle-tools/m5oczybm69?form_factor=desktop

**Comment by thomivy** [comment]
The JS imports were cleaned up, just to note :)
