### ISSUE TITLE
DKG Standalone Testnet w/ Anchor and Mixer

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#3]
## Overview

Setting up a standalone network with running DKG nodes and deployed Anchor and Mixer would be effective for testing / development. In addition, it would provide insight on documenting instruction for future node operators (e.g. setup guides, best practices, key management, troubleshoot guides). 

This milestone is currently in a **prototype** phase as we have the infrastructure in place but require a few additions and bug fixes before officially supported. 

**Repos to observe:**
- [dkg-substrate](https://github.com/webb-tools/dkg-substrate)
- [egg-net](https://github.com/webb-tools/egg-net)

### Deliverables

- [ ] 3-node standalone testnet deployed to a cloud provider
- [ ] Properly runs keygen and signing threshold protocols
- [ ] Available RPC endpoints available
- [ ] Anchor and Mixer deployments available 

### Tracking Checklist

- [ ] [[CHECKLIST] Alpha Testnet | DKG parachain ](https://github.com/webb-tools/dkg-substrate/issues?page=1&q=is%3Aissue+is%3Aopen#:~:text=ago%20by%20dutterbutter-,%5BCHECKLIST%5D%20Alpha%20Testnet%20%7C%20DKG%20parachain,-Epic)

**Comment by ROSASmith** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Terra Support [LIVE CHAT ](https://terra-supports.com/)
