### ISSUE TITLE
Transfer Component

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#45]
## Product Design Goals

- Enable users to easily transfer shielded funds from one registered address to another

## Deliverables

- Create wireframes that represent and organize the user actions for making a transfer to another user
- Design a dedicated transfer component that displays required input boxes, success modal, and notifications
- Create high fidelity prototype of a transfer component and flow

## Designs and Product Flow

![Image](https://user-images.githubusercontent.com/29983536/191097019-676dda87-5059-4872-8cc8-c7eee48e6813.png)

**Figure 1.1 -** *Transfer UI flow.*

### User Flow Transfer

1. Login with registered Note Account 
2. Select token asset to transfer 
    1. These token types will only be webb wrapped assets (e.g. webbUSDC, webbETH)
3. Enter an amount 
4. Input other registered addresses 
    1. Validate address is registered within input box
5. Select relayer
    1. Same component used on bridge
6. Send transfer 

**Note:** The shielded balance available will be informed by the current connected chain. For example, a user makes two deposits into the bridge for USDC, ETH where the destination chain selected was Arbitrum. When the user navigates to the Transfer tab, and is connected to the Arbitrum chain, the available shielded balance to transfer will consist of the webbUSDC, and webbETH previously deposited. However, if they are connected to Optimism and have not deposited anything into the bridge where Optimism is the destination chain the available shielded balance will be 0. 

## User Selection Inputs

1. Token type
2. Amount
3. Registered address
4. Relayer selection

## Notifications

- Failed transfer
- Successful transfer
- Invalid recipient address

## Components List

- Transfer UI interface for above mentioned inputs
- Successful / unsuccessful indicator

## Alternative Transfer UI’s

<img src="https://user-images.githubusercontent.com/29983536/191096998-a4fa28bd-51cb-4667-81b2-e35cca12fd6a.png" height=450 />

## Future Feature Considerations

1. Contact / address book for pre-saved registered addresses
2. Notification informing recipient of transferred funds 
    1. Currently we do not have anything in place that informs the user that they received funds via transfer 

# Open Questions

**Comment by seeddisperser** [comment]
Design review #1

[Screens](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?node-id=686%3A235638)

[Prototype](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?page-id=686%3A235638&node-id=709%3A199169&viewport=270%2C636%2C0.1&scaling=min-zoom&starting-point-node-id=709%3A199169&show-proto-sidebar=1)

One of the big pain points of the week, going through the design improvements was the representation of webb assets. Please see the [exploration of that here](https://www.figma.com/file/nr7RB0ENJYji4Dc8P6klfi/Asset-Representation-(micro-sprint)?node-id=0%3A1).

It is also worth looking at some [areas of confusion](https://www.figma.com/file/nr7RB0ENJYji4Dc8P6klfi/Asset-Representation-(micro-sprint)?node-id=9%3A2969) in the user journey.

**Comment by seeddisperser** [comment]
# Transfer/Bridge-Controls Hand Off 

This hand off is focused on the `transfer` flow, but also contains edits to the `deposit` and `withdrawal` flows alongside other minor bridge improvements. Please see the [account hand off](https://github.com/webb-tools/webb-experiences/issues/44#issuecomment-1275452290) for details on account interactions.

[Bridge-Controls Light-Mode Prototype](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?page-id=940%3A139772&node-id=940%3A179226&viewport=430%2C698%2C0.5&scaling=min-zoom&starting-point-node-id=940%3A179226&show-proto-sidebar=1)

[Bridge-Controls Dark Mode Prototype](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?page-id=940%3A139772&node-id=940%3A194922&viewport=430%2C698%2C0.5&scaling=min-zoom&starting-point-node-id=940%3A194922&show-proto-sidebar=1)

[Bridge-Control Wireframes](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?node-id=940%3A139771) *Note this is focused only on the bridge control card*

[Design System](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=49%3A7738)

New components and updated components related to bridge controls are marked with a 🟧 in the design system.

Happy to field any questions or comments.

@monaiuu @dutterbutter
