### ISSUE TITLE
[TASK] Hubble Bridge Statistics Page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#47]
## Overview

For Asset transfer details please refer to the PRD [here](https://www.notion.so/hicommonwealth/DRAFT-Hubble-Bridge-Statistics-PRD-97ebdfb9660d45349bd492ec0e035dd0).

**Comment by seeddisperser** [comment]
## Relevant Links

[Stats designs](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/Shielded-Pool-Stats?node-id=4%3A101&t=Ob5fWfM0IgvnDWxd-1)

[Components](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/Shielded-Pool-Stats?node-id=61%3A9325&t=Ob5fWfM0IgvnDWxd-1)

[Misc components](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/Shielded-Pool-Stats?node-id=63%3A4692&t=Ob5fWfM0IgvnDWxd-1)

### To be completed

- [x] Bridge stats overview page (concept designs in place)
- [x] Overall stats page navigation with DKG stats consideration 
- [x] Small details considerations to be reviewed
- [ ] Add components to the design system 
- [ ] Review edge cases

**Comment by monaiuu** [comment]
## Hubble Bridge Statistics - Handoff

Please see below for the handoff of Hubble Bridge Statistics Page. This handoff involves the Hubble Overview Page, and the Pool/Token Stats Page. 

For the Overview Page, the following is displayed:
* General statistics/data of Hubble Bridge
* List of shielded tokens available
* List of shielded pools available 

For the Pool/Token Page, the following is displayed:
* General info of pool/token
* General statistics/data of pool/token
* Distribution of token composition amongst various chains
* List of transactions 
* Pool-specific metadata

### [Hand-off Wireframes](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?node-id=381%3A63562&t=dL0J2QLzOVqi1aCD-1)

### [Hand-off Prototype](https://www.figma.com/proto/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?page-id=381%3A63562&node-id=381%3A63563&viewport=6865%2C-7128%2C0.5&scaling=contain&starting-point-node-id=381%3A63563)

### Screen Recording
https://user-images.githubusercontent.com/109539270/225698825-6b9b3789-aadf-41c1-9ec0-fcb60dad0d0c.mp4

**Comment by dutterbutter** [comment]
Closing in favour of handoff: https://github.com/webb-tools/webb-dapp/issues/1056
