### ISSUE TITLE
Crowdloan Flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#48]
## Product Design Goals

- Provide a intuitive and straightforward flow for the community to contribute to the crowdloan
- Our goal is to allow community members to easily contribute to the crowdloan, while understanding its purpose and their expected rewards

## Deliverables

- Create wireframes that represent and organize the user actions for interacting / contributing to the webb crowdloan
- Design a dedicated crowdloan component that displays key information regarding the crowdloan and allows users to submit transactions
- Create high fidelity prototype of a crowdloan component and flow

## Designs and Product Flow

![image](https://user-images.githubusercontent.com/29983536/191873027-c79d2bfb-a689-497d-b9b1-0afb3b7f5f6e.png)

**Figure 1.0** - *Crowdloan contribution UI flow*

## Feature Details

The Kusama Network allows Parachains to source tokens for their Parachain bids in a decentralized crowdloan. Webb will be conducting a crowdloan campaign to secure a Parachain slot on Kusama for the Tangle network.

Kusama is a sharded, multi-chain network that allows blockchains to connect for interoperability, scalability, and plug-and-play network security. To join the Kusama network, all parachains must participate in and win a unpermissioned candle auction to secure a slot on the network. Parachains can choose to raise KSM in a variety of ways in order to participate in the auction.

The crowdloan design page can be quite primitive. It just needs to have the single required form and information about the crowdloan. It should have a separate tab on the side navbar.

- Should list total amount contributed so far
- Contribution amount input box
    - Connects to users wallet
    - Able to select MAX to quickly input the maximum contribution amount allowed
- Display the users contribution amount
- Display the minimum amount you get for your contribution
- Button to initiate crowd loan tx
- Content for crowd loan page
- Modal indicating a successful crowdloan transaction

### UI Inspirations:

<img src="https://user-images.githubusercontent.com/29983536/191873625-6cacafd3-4cd4-4ffd-8a81-bbab76d346a6.png" height=350 />
https://crowdloan.parallel.fi/#/auction/contribute/polkadot/2012

<img src="https://user-images.githubusercontent.com/29983536/191873626-25482e24-61df-4318-817e-c0a157de80a7.png" height=350 />

<img src="https://user-images.githubusercontent.com/29983536/191873627-7f1ed037-0494-4ae1-8f61-89e1e01af303.png" height=350 />
https://crowdloan.astar.network/#/

## Notifications

Notifications that should be present should include, but not limited to, 

- Successful transaction 
- Transaction error 

## Components List

- Input box (should already have with webb-ui-kit)
- Crowdloan Card 
- Educational Content 
 
### Relevant Links

- [Crowdloan docs](https://docs.webb.tools/v1/crowdloan/overview/)
- [Crowdloan spec](https://www.notion.so/hicommonwealth/9219f508b838450584b20ac165bd02ba?v=1d802a922e264b3ea81be187dd1812b6)

# Open Questions

1. Should we have the crowdloan participation through the marketing site (more specifically Tangle Network site) rather than the dApp? Seems to be the norm of other parachain teams. Simply put, we design for a web page rather than the dapp, and functionality of which is included in the website rather than the dApp.

**Comment by dutterbutter** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.onfinality.io%2Fpublic-ws#/parachains/crowdloan

**Comment by monaiuu** [comment]
# Crowdloan Flow Hand-off [Wireframes + Prototype]

The only new component that will be updated in the design system is the ['Expansion Panels'](https://m1.material.io/components/expansion-panels.html) under FAQ. Other components such as the Countdown TImer should not be included in the design system due to its one time usage. Please note that small adjustments might be made upon the completion of the Tangle Website.

### [Wireframe File](https://www.figma.com/file/wq2gkDTWWuOwTmKQ7Ry1i7/%F0%9F%AA%99-Crowdloan?node-id=82%3A3434)
### [Figma Prototype](https://www.figma.com/proto/wq2gkDTWWuOwTmKQ7Ry1i7/%F0%9F%AA%99-Crowdloan?page-id=82%3A3434&node-id=82%3A3488&viewport=611%2C416%2C0.12&scaling=scale-down&starting-point-node-id=82%3A3488)
