### ISSUE TITLE
ECDSA Claims Flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#49]
## Product Design Goals

- Provide a intuitive and straightforward flow for the community to claim their contribution rewards 

## Deliverables

- Create wireframes that represent and organize the user actions for claiming their contribution rewards
- Design a dedicated claims component that displays key information regarding the crowdloan and allows users to claim their rewards
- Create high fidelity prototype of a claims component and flow

## Designs and Product Flow

![image](https://user-images.githubusercontent.com/29983536/191874282-273bc983-8831-4feb-96fd-80fd1c787888.png)

**Figure 1.0** - *ECDSA Claims UI flow*

## Feature Details

The purpose of ECDSA Claims page is to allow users to easily claim their crowdloan contribution rewards. The basic steps is to enter a valid Substrate based address, which depending on your contribution allow that user to claim some token rewards. 

### Current UI Flow

**Enter Address:**
<img width="464" alt="Screen Shot 2022-09-22 at 7 46 53 PM" src="https://user-images.githubusercontent.com/29983536/191874426-a4a72fa7-1af6-4897-9f52-cd2189afc480.png">

**Verify Signature and Claim:**
**Note: this is not a UI requirements**
<img width="474" alt="Screen Shot 2022-09-22 at 7 43 51 PM" src="https://user-images.githubusercontent.com/29983536/191874458-f3cfaac8-1244-4ae7-8584-2dc6f94dfca4.png">

### UI Inspirations:
- See: https://distribution.acala.network/

## Notifications

Notifications that should be present should include, but not limited to, 

- Successfully claimed rewards  

## Components List

- Input box (should already have with webb-ui-kit)
- ECDSA Claims Card 
- Educational content
 
# Open Questions

1. Should this be included in the marketing site rather than webb Dapp?

**Comment by monaiuu** [comment]
# ECDSA Claims Flow Hand-off [Wireframes + Prototype]
Similar to the Crowdloan Flow #48 the only new component that will be updated in the design system is the ['Expansion Panels'](https://m1.material.io/components/expansion-panels.html) under FAQ. Please note that small adjustments might be made upon the completion of the Tangle Website.

[Wireframe File](https://www.figma.com/file/y5oE5rmlHEKQ0tgevMvrHF/%F0%9F%AA%82-ECDSA-Claim-(Airdrop)?node-id=24%3A2118)
[Figma Prototype](https://www.figma.com/proto/y5oE5rmlHEKQ0tgevMvrHF/%F0%9F%AA%82-ECDSA-Claim-(Airdrop)?page-id=24%3A2118&node-id=24%3A4091&viewport=743%2C546%2C0.11&scaling=scale-down&starting-point-node-id=24%3A4091&show-proto-sidebar=1)
