### ISSUE TITLE
Remaining Bridge Improvements

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#54]
## Overview

While the bridge is ready to be handed off, there are areas that require additional consideration. These include:

- [ ] Education card
- [x] Side navigation
- [x] Top nav bar refinement 
- [x] Disclaimer component → achieving consistency
- [x] Unwrapping assets selection
- [ ] Informative error messages
- [x] Recover with secret note feature
- [x] Token icons (shielded & webb wrapped)
- [x] Naming conventions (e.g. webb wrapped XYZ & webb shielded XYZ)
- [x] Drop shadow usage

The changes that remain in these areas will be stylistic improvements that will unify the UI. The design teams suggestion would be to implement the above areas last so as not to waste dev time.

## Remaining Items

- [x] Transaction process component
    - need to establish stacking (i.e., what if there are failed state + success states in one component; how will that parent component behave?)
    - need to establish timing mechanism (how long will it be ‘sticky’ after a transaction has failed?)
    - withdrawal timeline
    - what happens when user taps on ‘view note’ & ‘details’?

- [x] Notes management
    - add secret note
    - delete secret note

- [ ] Tooltips
    - writing informative tooltips throughout the dapp
    - figuring out how to eliminate excess tooltips! (there are so many!)

**Comment by monaiuu** [comment]
### Transaction Process Component Updates: 

**Note**: Below updates are annotated in the [**Design System**](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System) in the page **'🟡  Transaction Progress Card'**. 

* Added `transfer` type to progress transaction cards
![Screen Shot 2022-10-17 at 2 09 56 PM](https://user-images.githubusercontent.com/109539270/196284022-8427f024-2102-4856-adb2-badcad32ba44.png)
* Removed `view note` link button, added `sync note` link button at `complete` state to allow users to update account conveniently after a transaction is complete
* Updated asset names/icons to reflect naming conventions across bridge UI
* Updated disclaimer content depending if new spend note is generated or not
![Screen Shot 2022-10-17 at 2 13 57 PM](https://user-images.githubusercontent.com/109539270/196284854-b9bb14a5-e7e6-4491-83dd-48ed9ecca3fa.png)

* Added overflow behaviour and established max length for component
![Screen Shot 2022-10-17 at 2 15 10 PM](https://user-images.githubusercontent.com/109539270/196284960-a2730891-d373-4e8a-bf83-43c1740b4461.png)

* Added `dismiss` link button to allow users to close completed/failed card(s)
![Screen Shot 2022-10-17 at 2 00 39 PM](https://user-images.githubusercontent.com/109539270/196283510-6d17388d-0ad8-4117-a1aa-a69041bcefd1.png)
* Updated timing mechanics (from `seconds` to `just now` to simplify time display) 
![Screen Shot 2022-10-17 at 2 06 36 PM](https://user-images.githubusercontent.com/109539270/196283484-ff331b20-7347-4109-a7b6-86b81a22b3cc.png)

Any questions or feedback do not hesitate to let me know! 
@AtelyPham @dutterbutter @seeddisperser

**Comment by monaiuu** [comment]
For the remaining tasks (Informative Error Messages & Tooltips), can we defer these tasks to micro-sprints after deployment to evaluate how to address these issues in contexts? @dutterbutter 

For educational cards, I believe @seeddisperser will address them according to the visual language & branding based on the marketing website.

**Comment by dutterbutter** [comment]
Considering this task closed, and creating new issues for remaining items (Informative Error Messages, education card)
