### ISSUE TITLE
EPIC: Design and Copy of Webb marketing site

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#56]
## Overview

We want to implement the new designs for our webbsite. The new website will consist of x pages, with new content and assets. Below you’ll find everything required to implement the new designs.

### Task Checklist

- [x] #68 
- [x] #69 
- [x] #70 
- [x] #71 

#### Linked Pages

- Docs
- Careers 
- Bridge Dapp 

### WIP Copy

- [Marketing Site Content](https://www.notion.so/hicommonwealth/Marketing-Site-Content-b252529151804c8ba0e85cdde0d5d486)

## Relevant Links

- **Docs link** - http://docs.webb.tools/
- **Careers link** - https://angel.co/company/webb-4/jobs
- **Twitter -** https://twitter.com/webbprotocol
- **Discord -** https://discord.com/invite/cv8EfJu3Tn
- **Github -** https://github.com/webb-tools
- **Telegram -** https://t.me/webbprotocol

**Comment by dutterbutter** [comment]
### Checklist 

- [ ] Site designs 
- [x] Marketing content for Webbsite

#### Open Questions 

1. Scope of marketing site (e.g. should we include Tangle Network site in this scope)?

**Comment by seeddisperser** [comment]
Design of the marketing website is moving closer to completion.

The landing page can be [found here](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=592%3A12364). I've commented where additional copy is needed, and what illustrations require additional attention. 

The prototype of the onscroll action can be [found here](https://www.figma.com/proto/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?page-id=592%3A12364&node-id=610%3A14190&viewport=808%2C788%2C0.13&scaling=min-zoom&starting-point-node-id=610%3A16668). 

I've also started pulling together a document [detailing the visual language](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=610%3A29035). The goal is to build this out into a document that defines the feel and look of things beyond just the design system. Right now it's a WIP and I hope to build this out with @monaiuu 

-----

@dutterbutter  To complete the remaining pages, additional copy is needed for:
- [Tangle Network Page](https://www.notion.so/hicommonwealth/Tangle-Network-Page-eae561786ef44375bd6cfdc17bf1c785)
- [Shielded Pool Protocol Page](https://www.notion.so/hicommonwealth/Shielded-Pool-Page-db64a52a1d76472d8908d49fa4bd4b51)
- [Shielded Identity Protocol Page](https://www.notion.so/hicommonwealth/Shielded-Identity-Protocol-Page-0eb92887c3c84b92a1c0014ac001e640)
- [Research Page](https://www.notion.so/hicommonwealth/Research-Page-2a0d9312b1474c549384eb41e14edded)
- [Community Page](https://www.notion.so/hicommonwealth/Community-Page-448027ef822d43ce89bfd1c1c81fc08f)

Finally details about 3d artists to render illustrations can be [found here](https://www.notion.so/hicommonwealth/3d-Illustrators-8e56e464c25d4ad7b826de20455b2b28).
