### ISSUE TITLE
Tangle Network Website

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#57]

**Comment by monaiuu** [comment]
### Tangle Webbsite Planning [WIP]

## **👉** Overivew:
The Tangle Network Webbsite is the landing page of the Tangle Network]. The website is the launchpad for our target audience to engage and participate with the network. It should be concise, easy-to-understand, and closely-tied-to with Webb’s branding & visual language. 

## **👥** Target Audience:

1. **Developers**
2. **Collators**
3. **Institutions & Investors**
4. **Defi Users**
    - crowdloan participation + airdrop claims
    - to learn more about $TNT

## 🎯 Goals:

1. Introduce Tangle Network to our target audience.
2. Invite target audience to engage with the Tangle Network.
3. To establish trust & legitimacy — the Webb Ecosystem.

## **👣** Traffic Sources:

- Polkadot/Kusama (parallel finance, parachains)
- Exchanges
- Press Releases
- Social Medias
- Community Channels
- Webb Marketing Site

## 📃 Site Content

### 1. **Top Navigation Section:**
- About
    - Docs
    - Github
- Network
    - Block Explorer [Subscan]
    - Run Collator/Validator
    - Staking [soon]
- TNT Token
    - Tokenomics
    - Get Token
- Built on Tangle
    - WebbBridge
- Community
    - Twitter
    - Discord
    - Telegram
    - Commonwealth
    - Blog
- **Visit WebbdApp** [main CTA]

### 2. Hero Section:

**Tangle Network — The canary network for zero-knowledge cross-chain messaging [TBD].** 

### 3. Body Section****

***What is Tangle Network?***
[Could you help illustrate what Tangle Network is?] [3 Sentences]
(below are from Drew)
- The tangle network is a threshold signature layer 0 blockchain aimed at connecting zero knowledge applications across the Web3 ecosystem. 
- The tangle network validates and relays cross chain zero messages using threshold ECDSA signatures. 
- The tangle network utilizes a Proof of Stake authority selection system to enable permissionless participation in securing cross chain zero knowledge applications. 
- The tangle network doubles as hub for routing cross chain zero knowledge messages and for anchoring itself as a bridge endpoint for cross chain zero knowledge applications in the Polkadot and Kusama ecosystems. 
- The tangle network validators rotate their participants in frequent sessions to allow for healthy growth to the underlying security of its cross chain zero knowledge message routing system. 


***How to engage with Tangle?***
[What are the ways people can engage with Tangle Network?]

- Try Webb dApp - Bridge.
- Become a Collator
- Join Social
- Check Airdrop
- Stake (coming soon)

### 4. **Footer:**

- Get the latest news [subscribe]
- Social Channels

---

## General Requirements

- Integrate Crowdloan Participation Page
- Integrate Airdrop Claim Page

[https://www.figma.com/file/wq2gkDTWWuOwTmKQ7Ry1i7/%F0%9F%AA%99-Crowdloan?node-id=86%3A4904](https://www.figma.com/file/wq2gkDTWWuOwTmKQ7Ry1i7/%F0%9F%AA%99-Crowdloan?node-id=86%3A4904)

[https://www.figma.com/file/y5oE5rmlHEKQ0tgevMvrHF/%F0%9F%AA%82-ECDSA-Claim-(Airdrop)?node-id=24%3A4613](https://www.figma.com/file/y5oE5rmlHEKQ0tgevMvrHF/%F0%9F%AA%82-ECDSA-Claim-(Airdrop)?node-id=24%3A4613)

### Design Requirements:

- Tangle Logo
- Graphics that illustrate Tangle Network

## Open Questions:

- What is the URL of Tangle Network?
- What is the main CTA of the top navigation? Where do we want to direct users?

## OKRS [TBD]

- Measure click through rates
- Email subscription  #s (mailchimp?)
- Track how much users join our social channels via Tangle Webbsite
- Track incoming traffics


***For latest update on this Brief, please refer to Notion Doc (https://www.notion.so/hicommonwealth/Tangle-Webbsite-Planning-72a52c84b9c34709b2075296d9ed826a)***

**Comment by dutterbutter** [comment]
Closing as dev hand off issue posted: https://github.com/webb-tools/webb-dapp/issues/1010
