### ISSUE TITLE
Education Card Components

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#58]
Draft to fit the current Dapp configurations

https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1341%3A41299&t=rWlfasfgIfKRaLZu-1

**Comment by dutterbutter** [comment]
@seeddisperser any chance this can be ready this week? It would be nice to include this in the initial release. See: https://github.com/webb-tools/webb-dapp/issues/979

**Comment by seeddisperser** [comment]
Sure. Can get this out shortly.
