### ISSUE TITLE
Stats Page Design Improvements

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#62]
## Overview

A list of items to track design improvements for the stats dapp. 

- [x] Increase the number of stats displayed and remove abundance of white space (Block #, Session #)

![Image](https://user-images.githubusercontent.com/29983536/199091064-c4d70f0c-f8e3-407a-a26d-42163906e831.png)

- [x] Redesign proposal types donut chart 

Might be better to show data in a table form

- [x] Change threshold history diagram from bar chart to line chart

**Comment by dutterbutter** [comment]
Other design updates for improved stats page:

- More granular back page navigation, when a user navigates through the 'Details' link it can become confusing where they are among the pages. Adding a page breadcrum, similar to our docs site might improve a users ability to navigate. 

**Example breadcrum but in a forward direction:**
![Image](https://user-images.githubusercontent.com/29983536/200409228-24a56b4a-0197-424d-8a4c-887601f02f7e.png)

- Updating the progress bars to include more granular data (e.g. days). When viewing the existing progress bar the info contained is not as detailed as it could be. We could include a hover stat or gradient coloring to depict a different hr or day of progress.

**Comment by monaiuu** [comment]
### Stats Page Design Improvements[Wireframes + Prototype]


[Wireframe File](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?node-id=1152%3A113488&t=rfvHAhcHAfZLseYY-1)
[Figma Prototype](https://www.figma.com/proto/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?page-id=1152%3A113488&node-id=1167%3A152573&viewport=7518%2C-949%2C0.26&scaling=scale-down&starting-point-node-id=1167%3A152573)

Here are the updated [wireframes](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?node-id=1152%3A113488&t=6Mofy0v907uY9DMn-1) and [prototype](https://www.figma.com/proto/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?page-id=1152%3A113488&node-id=1167%3A152573&viewport=7518%2C-949%2C0.26&scaling=scale-down&starting-point-node-id=1167%3A152573) for the DKG stats page. Below is the summary of changes:

Sitewide:

- Replaced Keys Overview as the landing of the DKG Stats page
- Added more data sources to reflect the status of the network below top nav
- Added breadcrumbs to improve the navigation experience
- Updated top nav dropdown
- added connected node
- removed expand feature for custom data source
- removed light/dark theme change redundancy
- Updated all progress bars to linear gradient for improved visual experience

Key Page:

- Updated the Active Key progress bar to include the display of signed proposals
- added number of proposals signed by type
- hover state enables users to view the details of each proposal
- Removed Next Key component

Proposals:

- Added proposal type in immediate view when users view proposal details
- Replaced donut chart with stacked graph in Proposals Overview

Authorities:

- Updated bar graphs to line graphs
- Added line grids behind the network threshold graphs for a better visual experience

For more detailed documentation on the changes, please refer to the figma doc comments & annotations.
