### ISSUE TITLE
Note account creation flow for bridge

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#63]
## Current Note Account Creation Flow

![Image](https://user-images.githubusercontent.com/29983536/199574564-1bb862ff-bd3f-47a4-a441-9cc91bdca180.png)

1. Users must create a `NoteAccount` prior to depositing 
2. Users can create a `NoteAccount` with MetaMask
    1. MetaMask `NoteAccount` uses the first 32 bytes of the signed message from the MetaMask account as the secret seed
3. Users can load notes from the AccountManager modal, and view secret notes once created
4. Users can login by using MetaMask with the same account where they can view their past notes
    1. **Note:** This is currently only stored in `LocalStorage` so if the user logs in from a different machine or clears their browser storage they will not see these past notes

## Future Note Account Creation Flow

- We should remove the ability to create random NoteAccount and require users to make use of MetaMask / Wallet signing

**Comment by monaiuu** [comment]
# Note Account Creation Flow Hand-off [Wireframes + Prototype]
Here is the hand-off wireframes & prototype for [Note account creation flow for bridge #63](https://github.com/webb-tools/webb-experiences/issues/63). This flow assumes the user has a wallet connected but gets an in-between state on the Bridge UI. The user cannot make transactions until a Note Account is created (the main CTA on the bridge control card displays ‘Create Note Account’). 

### [Wireframe File](https://www.figma.com/file/VHrPTN7saAlW1M64BjdjxQ/%F0%9F%91%A4-Account?node-id=562%3A149221)
### [Figma Prototype](https://www.figma.com/proto/VHrPTN7saAlW1M64BjdjxQ/%F0%9F%91%A4-Account?page-id=562%3A149221&node-id=664%3A139038&viewport=-8102%2C3148%2C1.19&scaling=scale-down&starting-point-node-id=664%3A140053&show-proto-sidebar=1)
