### ISSUE TITLE
[TASK] Accessibility audit of component library

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-experiences#88]
Run testing on the component library for consistency, contrast and accessibility. 

check = passed

- [x] Accordion
- [ ] AmountInput (contrast failed) design
- [ ] AmountMenu (contrast failed) design 
- [x] Avatar
- [ ] AvatarGroup (alt-text failed, should be a variant of Avatar) dev
- [x] breadcrumbs
- [ ] BridgeInputGroup (contrast failed) design
- [x] Button 
- [x] card
- [x] card table
- [ ] ChainInput (contrast failed) design 
- [ ] CheckBoxMenu (ARIA violation) dev
- [ ] CheckBox (Label Missing) dev
- [ ] Chip (contrast failed) design
- [x] Collapsible 
- [ ] CopyWithToolTip (Missing Text Description For Screenreader) dev
- [ ] Disclaimer (contrast failed)
- [x] Divider
- [x] DropdownMenu
- [ ] FixedAmount (Contrast failed ARAI violation) design, dev
- [x] infoitems
- [ ] Inputs (missing label) dev
- [ ] KeyValueButton (default should have no copy button, variant with copy tooltip should be composed of `KeyValueButton` and `CopyWithToolTip`) dev
- [ ] Label (ARIA violation) dev
- [ ] LabelWithValue (ARIA violation) dev
- [x] MenuItem
- [x] Pagination
- [ ] Progress (ARIA Violation) dev
- [ ] RecipientInput (ARIA Violation Contrast Failure) Dev, Design
- [ ] RelayerInput (ARIA Violation Contrast Failure) Dev, Design
- [ ] SelectShieldedAsset (ARIA Violation Contrast Failure) Dev, Design
- [ ] Slider (ARIA Violation) dev
- [x] Stats
- [ ] Switcher (needs alt text) dev
- [x] Tabs
- [ ] ThemeSwitcherButton (needs alt text, also, why is this its own component?) dev
- [ ] TimePRogress (ARIA violation) dev
- [ ] Timeline (ARIA violation) dev
- [x] Titlewithinfo
- [ ] TokenInput (ARIA violation) dev
- [x] Tokenpair
- [x] TokenRing
- [x] TokenSelector
- [ ] Tooltip (text too small) design
- [ ] TopNavigationMenu (needs alt text) dev

**Comment by dutterbutter** [comment]
@monaiuu need to re-assess what has been addressed with latest PRs.
