### ISSUE TITLE
[PROCESS] Bridge User Flow Testing

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-experiences#89]
Run through the bridge with team, to ensure actions are working correctly, and to establish design improvements.

**Comment by monaiuu** [comment]
### Usability Testing Framework & Notes

Below are the documents used to guide and conduct usability testing:

[Usability Testing Guideline](https://www.notion.so/hicommonwealth/Usability-Testing-Guideline-902369724b424daa867e866b1f0c25a4)
[Session Output - Round 1
](https://www.notion.so/hicommonwealth/Session-Output-Round-1-0c187e5ff8524f97a15ec15878160be8)
