### ISSUE TITLE
Bridge Design Improvements

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-experiences#90]
This issues is intended to capture issues and improvements to the bridge experience.

Underway:
- https://github.com/webb-tools/webb-experiences/issues/93
- https://github.com/webb-tools/webb-experiences/issues/92

High Priority 
- https://github.com/webb-tools/webb-experiences/issues/94
- https://github.com/webb-tools/webb-experiences/issues/95
- https://github.com/webb-tools/webb-experiences/issues/50
- https://github.com/webb-tools/webb-experiences/issues/65
- https://github.com/webb-tools/webb-experiences/issues/58

Backlog

- https://github.com/webb-tools/webb-experiences/issues/59
- https://github.com/webb-tools/webb-experiences/issues/60
- https://github.com/webb-tools/webb-dapp/issues/954

Big Challenging Updates That Require More Thought
- https://github.com/webb-tools/webb-experiences/issues/96
- https://github.com/webb-tools/webb-experiences/issues/97

also see:
https://github.com/webb-tools/webb-dapp/issues/876

**Comment by dutterbutter** [comment]
@seeddisperser I do not think the following issues require design specific work as they are quite straight forward to implement:
- https://github.com/webb-tools/webb-dapp/issues/950
- https://github.com/webb-tools/webb-dapp/issues/945
- https://github.com/webb-tools/webb-dapp/issues/944
- https://github.com/webb-tools/webb-dapp/issues/943
- https://github.com/webb-tools/webb-dapp/issues/936
- https://github.com/webb-tools/webb-experiences/issues/94

**Comment by dutterbutter** [comment]
@seeddisperser I think mobile views is going to be prioritized to HIGH
