### ISSUE TITLE
Transaction Processing Card Improvements

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-experiences#91]
## Overview 
The transaction processing card appears when a user initiates a transaction and informs the user of each state the tx is in. Those states can be summarized as processing, successful, and failed. Reviewing the cards it looks like we have 3 levels of redundant information that could be minimized. @monaiuu @seeddisperser thoughts? 

![procssing-card-copy](https://user-images.githubusercontent.com/29983536/215606835-2621419b-8a4c-48b3-8e24-78d8702a7d2b.png)

**Comment by monaiuu** [comment]
we could certainly reduce the redundancy of "X transaction in progress" (2), whereas the for "sending transaction" (3) we could detail the transaction process such as 'generating ZK proofs, fetching leaves, sending to recipient etc.) WDYT?

<img width="787" alt="Screenshot 2023-01-31 at 7 22 59 AM" src="https://user-images.githubusercontent.com/109539270/215609727-b3bf742f-7ea8-44cf-9add-38dd977cfd70.png">

**Comment by dutterbutter** [comment]
@monaiuu that could work for the processing state but we will still need to address the success and failed state as those states also present duplicated messaging. For instance when a tx fails it says that 3 times.
