### ISSUE TITLE
[TASK] Surface Network Selection on Transfer

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-experiences#95]
## Overview

Right now there is no way to choose a network on transfer other than by using the top nav. This is confusing because it breaks the pattern established by both deposit and withdraw. 

### Relevant Figma Links

[Transfer selection](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/Shielded-Pool-Stats?node-id=126%3A27151&t=Ob5fWfM0IgvnDWxd-1)

**Comment by monaiuu** [comment]
## Description
Currently, when landing on the transfer page, the network of the bridging token is not immediately apparent, which can lead to confusion for users who are trying to initiate a transfer. This is particularly problematic when the bridging token can be used on multiple networks, as it can be difficult to determine which network is currently selected.

In addition, there is confusion in the logic of the default state displayed on the transfer page. The current default state may not be intuitive or reflective of the user's intended action, which can lead to errors and frustration.

To improve the user experience on the transfer page, proposing the following changes:


### Proposed Solutions

- Add `Source Chain Selector` next to the bridge token to clearly indicate the network of the displayed bridge token.
![Image](https://user-images.githubusercontent.com/109539270/231284863-49951db3-7faa-407c-93d2-953811d7ba91.png)

- Prevent scenarios whereby we display 'bridging token' different from the connected chain. 
![Image](https://user-images.githubusercontent.com/109539270/231283225-7b24beff-a329-4cb3-84a4-1ff8ba82a7b7.png)

- When the user has no available spend note on connected chain, display `unfilled state` of the bridging token selector.
![Image](https://user-images.githubusercontent.com/109539270/231287860-d945746f-5c43-4418-bd16-f7883da1a944.png)

**Comment by dutterbutter** [comment]
Closing in favour of https://github.com/webb-tools/webb-dapp/issues/1103
