### ISSUE TITLE
[TASK] Standardize Asset, network, and relayer treatment

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-experiences#99]
## Overview

To improve clarity and standardize how elements are represented, we need to implement rules for how assets, networks, relayers, and shielded assets are depicted. 

### Relevant Figma Links

[Concept design](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/Shielded-Pool-Stats?node-id=183%3A62169&t=dU0NHS7dsnpEgQAJ-1)

**Comment by monaiuu** [comment]
## Handoff
To improve clarity and standardize how elements are represented, we need to implement rules for depicting assets, networks, relayers, and shielded assets. Please take a look below for the updates required.


![Image](https://user-images.githubusercontent.com/109539270/230466635-8771030f-e60f-498c-a3a1-8c02ea829ae0.png)


- For `token` representation, we will remain using `circular` shapes to represent tokens.

- For `network/chain` representation, we will update to a `rectangular` shape to represent networks.

- To align with this update, the `chain chips` previously implemented will require an update to their `radius` to align with the chain representation.

- For `relayer` treatment, we will use a `hexagon` shape to represent all relayers to establish trust in using relayers.

- For `shielded pools/assets`, we will use a `shield` shape to represent its double meaning.


### Design System Updates
These components have been added to the design system; please reference the following pages for reference:

- **'🟢  [Avatars](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=30%3A352&t=zL5xxCWbLFEeiJRw-1)'** for added relayers and shielded token/pools treatment.
![Image](https://user-images.githubusercontent.com/109539270/230469065-709781fa-d217-46ad-bc6a-3d75e82197bd.png)

- **'🟢  [Chain Icons](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=4746%3A101498&t=zL5xxCWbLFEeiJRw-1)'** for updated chain icon display & chain chips display.
![Image](https://user-images.githubusercontent.com/109539270/230469089-03e3a2e2-a37e-4883-b689-569b41d36643.png)

Please note for this update, we will also have to ensure all dependent components are updated accordingly. I have audited and reviewed the entire design system and updated the component treatments accordingly. This update has also been pushed and should now similarly apply to all project files within Figma.
